#!/bin/bash
#this is a log zip backup script update at 2015 by zhuhj10338
#59 23 * * * /home/username/workspace/scripts/log_7z>/home/username/workspace/scripts/log/log_7z.log;

TMPYEAR=`date +%y`
TMPDATE=`date +%m%d`
TMPWEEK=`date +%w`
. /home/trade/.bash_profile
export PATH=$PATH:/usr/local/bin;

cd /home/trade/workspace

7za a -r -t7z /home/trade/logback/runlog_20${TMPYEAR}${TMPDATE}.7z runlog.log.*

date

echo "zip success!"

rm /home/trade/workspace/runlog.log.*

find /home/trade/logback/ -mtime +2 -type f -name '*.7z' -exec rm -f {} \;

