#!/bin/bash
#This is a log backup and 7-zip script update at 20151205 by zhuhj10338
#59 23 * * * /home/$USERNAME/workspace/scripts/log_7z>/home/$USERNAME/workspace/scripts/log/log_7z.log;

TMPYEAR=`date +%Y`
TMPDATE=`date +%m%d`
TMPWEEK=`date +%w`
TMPBEGINTIME=`date +%T`
USERNAME=`whoami`
. /home/$USERNAME/.bash_profile
export PATH=$PATH:/usr/local/bin;

cd /home/$USERNAME/workspace

echo "BACKUP DATE:"$TMPYEAR $TMPDATE

echo "BACKUP BEGIN TIME:"$TMPBEGINTIME

7za a -r -t7z /home/$USERNAME/logback/tradelog_${TMPYEAR}${TMPDATE}.7z tradelog/hsrm.queue_to_ufr.h3uft_queue_ls_a

date

echo "zip success!"

rm /home/$USERNAME/workspace/log/*

find /home/$USERNAME/logback/ -mtime +2 -type f -name '*.7z' -exec rm -f {} \;

TMPENDTIME=`date +%T`
echo "BACKUP END TIME:"$TMPENDTIME
