#!/bin/bash
#this is a log zip backup script update at 2015 by zhuhj10338
#59 23 * * * /home/web/scripts/log_7z>/home/oracle/scripts/log/log_7z.log;

TMPYEAR=`date +%y`
TMPDATE=`date +%m%d`
TMPWEEK=`date +%w`
TMPBEGINTIME=`date +%T`
USERNAME=`whoami`
. /home/$USERNAME/.bash_profile
export PATH=$PATH:/usr/local/bin;

cd /home/$USERNAME

echo "BACKUP DATE:"$TMPYEAR $TMPDATE

echo "BACKUP BEGIN TIME:"$TMPBEGINTIME

./killdbsync

cd /home/$USERNAME/apache-tomcat-7.0.57

7za a -r -t7z /home/$USERNAME/logback/log_20${TMPYEAR}${TMPDATE}.7z logs

date

echo "zip success!"

rm  /home/$USERNAME/apache-tomcat-7.0.57/logs/*
find /home/$USERNAME/apache-tomcat-7.0.57/ -mtime +7 -type f -name '*.7z' -exec rm -f {} \;
cd /home/$USERNAME
. /home/$USERNAME/.bash_profile
./rundbsync

TMPENDTIME=`date +%T`

echo "BACKUP END TIME:"$TMPENDTIME

