#!/bin/bash
#this is a log zip backup script update at 2015 by zhuhj10338
#59 23 * * * /home/web/scripts/log_7z>/home/oracle/scripts/log/log_7z.log;

TMPYEAR=`date +%y`
TMPDATE=`date +%m%d`
TMPWEEK=`date +%w`
. /home/web/.bash_profile
#export PATH=$PATH:/usr/local/bin;

cd /home/web

./killweb

cd /home/web/apache-tomcat-7.0.57

7za a -r -t7z log_20${TMPYEAR}${TMPDATE}.7z logs

date

echo "zip success!"

rm  /home/web/apache-tomcat-7.0.57/logs/
find /home/web/apache-tomcat-7.0.57/ -mtime +14 -type f -name '*.7z' -exec rm -f {} \;
cd /home/web
. /home/web/.bash_profile
./runweb

